base.matrix <- matrix(c(1, 2, 3, 4), 2, 2)
m <- makeCacheMatrix(base.matrix)
print(cacheSolve(m))
print(cacheSolve(m))
print("------------")
base.matrix <- matrix(c(1, 0, 0, 1), 2, 2)
m <- makeCacheMatrix(base.matrix)
print(cacheSolve(m))
print(cacheSolve(m))